Feat(#8) 공용모다컴포넌트
sprint6-part3-team3/Coworkers pull request #20
Opened 2024-07-28 04:26 UTC by Han-wo

## #️⃣ 이슈

- close #8 

## 📝 작업 내용

공용모달 컴포넌트를 제작했습니다

## 📸 결과물
![image](https://github.com/user-attachments/assets/46c3ac01-ceb0-4f85-92a5-2581089162ee)

![image](https://github.com/user-attachments/assets/82276b9a-310e-425f-80f1-070d45955065)

![image](https://github.com/user-attachments/assets/3d9bccc5-1ae3-4aa7-8b4c-f486de392eca)

## ✅ 체크 리스트

- [x] 적절한 Title 작성
- [x] 적절한 Label 지정
- [x] Assignee 및 Reviewer 지정
- [x] 로컬 작동 확인
- [x] Merge 되는 브랜치 확인

## 👩‍💻 공유 포인트 및 논의 사항
로컬동작 확인은 테스트 페이지에서 확인후 삭제하여 PR을 올렸습니다(스토리북에서 확인 가능합니다!)

경고모달과 일반모달을 나눌려했는데 그냥 아이콘 자체를 프롭으로 넘기는게 더 편할거같아서 아이콘까지는 프롭으로 넣었습니다

title과 description 은 기본으로 들어가있는데 피그마를 보면 description이 있을때와 없을때 제목과 컨텐츠 사이에 마진이 달라서 조건부로 넣어줬는데 PR을 올리면서 생각해보니까 children으로 넣는 컨텐츠에서 마진을 조정해도 될거같네요...

![image](https://github.com/user-attachments/assets/e933d78c-bd7b-4a5c-beb8-8280d2c29d5a)

![image](https://github.com/user-attachments/assets/91fad365-73ea-4ea4-99b2-aba662b211fd)

2024-07-28 05:37 UTC, easyhyun00 requested changes
모달 종류가 너무 많아서 고려해야 될 사항이 많은데 너무 잘 만드신거 같아요!! 👍

2024-07-28 05:37 UTC, easyhyun00 commented on src/components/common/modal/common-modal.tsx
> +  const getTitleMarginClass = () => (description ? "mb-8" : "mb-24");
p4)
함수보다는 상수를 사용하는게 더 좋을 거 같습니다!
`const titleMarginClass = description ? "mb-8" : "mb-24";` 이런식으로?

2024-07-28 05:37 UTC, easyhyun00 commented on src/components/common/modal/common-modal.tsx
> +    <div className="fixed inset-0 flex size-full items-center justify-center overflow-y-auto bg-background-primary/50">
p4)
모달같은 경우는 기존 DOM 구조에서 벗어나서 렌더링 하는 것이 독립성 및 접근성 측면에서 더 좋다고 해서
create portal 사용해보는 거 추천합니다!
https://ko.react.dev/reference/react-dom/createPortal

2024-07-28 05:37 UTC, easyhyun00 commented on src/components/common/modal/common-modal.tsx
> +    <div className="fixed inset-0 flex size-full items-center justify-center overflow-y-auto bg-background-primary/50">
아 그리고 `z index` 로 필요해보입니다!
너무 바라는 게 많아 보이긴 한데...😅 모달 외부 영역 클릭 했을 때 닫히는 것도 있으면 좋을 거 같아요!

2024-07-28 05:37 UTC, easyhyun00 commented on src/components/common/modal/common-modal.tsx
> +  children?: ReactNode;
```js
/** 이런식으로 주석 달면 아래 각 props 에 대한 설명이 스토리북에 작성됩니다!  */
isOpen: boolean;
/** 주석~~  */
onClose: () => void;
```

2024-07-28 06:00 UTC, Han-wo commented on src/components/common/modal/common-modal.tsx
> +  children?: ReactNode;
아 참고해서 수정할게요!!

2024-07-28 06:02 UTC, Han-wo commented on src/components/common/modal/common-modal.tsx
> +    <div className="fixed inset-0 flex size-full items-center justify-center overflow-y-auto bg-background-primary/50">
외부클릭은 나중에 지현님이 만드신 훅 머지 되면 그때 추가해 놓겠습니다!!

2024-07-28 06:03 UTC, Han-wo commented on src/components/common/modal/common-modal.tsx
> +  const getTitleMarginClass = () => (description ? "mb-8" : "mb-24");
넵!!

2024-07-28 06:06 UTC, easyhyun00 commented on src/components/common/modal/common-modal.tsx
> +    <div className="fixed inset-0 flex size-full items-center justify-center overflow-y-auto bg-background-primary/50">
모달같은 경우는 마우스 이벤트로 외부 영역 클릭할 필요없이 이미 외부 영역을 만들었기 때문에 거기에 ref 랑 onClick 이벤트 사용해서 
`e.target === modalRef.current && onClose();` 이런식으로 바로 할 수 있습니다!

2024-07-28 07:03 UTC, Han-wo commented on src/components/common/modal/common-modal.tsx
> +    <div className="fixed inset-0 flex size-full items-center justify-center overflow-y-auto bg-background-primary/50">
아항 감사합니다 !!

2024-07-28 07:07 UTC, JHmeatschool commented
공용 모달을 사용하기 쉽게 만들어주시려고 고민 많이 하신 것 같아 감사합니다 ㅠㅠ 덕분에 작업이 훨씬 편해질 것 같아요!

2024-07-28 07:07 UTC, JHmeatschool approved these changes

2024-07-29 03:40 UTC, easyhyun00 approved these changes

2024-07-29 03:42 UTC, merged