✨ Feat(#10) side menu 제작
sprint6-part3-team3/Coworkers pull request #30
Opened 2024-07-29 10:44 UTC by JHmeatschool

## #️⃣ 이슈

- close #10  

## 📝 작업 내용

로그인했지만 팀이 없는 경우, 로고와 유저 이름이 보이도록 추가했습니다
navbar 사이드 메뉴를 추가했습니다!
임시로 모양만 넣어봤습니다. 나중에 실제 데이터 넣을 예정입니다.
팀 추가하기 버튼은 버튼 pr 머지되면 바로 추가하겠습니다.

## 📸 결과물

스토리북을 봐주세요

## ✅ 체크 리스트

- [ ] 적절한 Title 작성
- [ ] 적절한 Label 지정
- [ ] Assignee 및 Reviewer 지정
- [ ] 로컬 작동 확인
- [ ] Merge 되는 브랜치 확인

## 👩‍💻 공유 포인트 및 논의 사항

드롭다운 메뉴에서 classname을 prop으로 받을수있게 조금 수정했습니다..!
지현님이 만들어주신건데 맘대로 수정해서 죄송합니다 ㅠㅠ 😭

2024-07-29 11:17 UTC, easyhyun00 requested changes

2024-07-29 11:17 UTC, easyhyun00 commented on src/components/common/nav-bar/index.tsx
> +              <DropDown handleClose={closeDropDowns}>
p2)
드롭다운이 제대로 안 딛히는 오류가 있어요! 
그냥 `<DropDown handleClose={teamDropdown.handleOff}>` 이렇게 해야 됩니다! 아래에도요!

2024-07-29 11:17 UTC, easyhyun00 commented on src/components/common/nav-bar/index.tsx
> +            </DropDown>
p4)
아래에도 똑같은게 있어서 nav-bar 안에 파일 하나 만들어서 컴포넌트 분리하는 게 좋아보여요! 팀 드롭다운도 분리하는 게 좋아보이네요!

2024-07-29 11:17 UTC, easyhyun00 commented on src/components/common/drop-down/menu.tsx
>          exit={{ opacity: 0, scale: 0.5, x: 20, y: -50 }}
p5)
여러 곳에서 사용되는데 x 좌표에도 애니메이션이 있어서 별로 안 예쁘네요🤔
아래코드로 수정 부탁드립니다!
```js
        initial={{ opacity: 0, scale: 0.5, y: -70 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.5, y: -70 }}
```

2024-07-29 11:17 UTC, easyhyun00 commented on src/components/common/nav-bar/index.tsx
> +                </DropDown.Trigger>
p5)
트리거 되는 영역을 늘려서 team 이름 클릭해도 열리면 더 좋을 거 같아요! 아래도 유저 이름 클릭해도 열리게!?

2024-07-29 11:34 UTC, JHmeatschool commented on src/components/common/nav-bar/index.tsx
> +              <DropDown handleClose={closeDropDowns}>
바로 수정했습니다! 감사합니다

2024-07-29 13:17 UTC, easyhyun00 approved these changes

2024-07-30 08:25 UTC, Han-wo approved these changes
고생하셨습니다 !!

2024-07-30 09:06 UTC, merged